### ISSUE TITLE
bright status bars in vim and tmux

### ISSUE THREAD

**Issue by jgallen23** [philj56/base16-crosh#1]
I have been using the themes here: https://github.com/cbreeden/base16-secure-shell, but I noticed yours is more up to date, but when I applied them, my status bars got a little bright.  Maybe some of the colors got swapped?

![screenshot 2017-11-10 at 4 39 28 pm](https://user-images.githubusercontent.com/27936/32684152-cb22ddd6-c635-11e7-8ebb-346dc49d8a69.png)

**Comment by philj56** [comment]
Sorry for the late reply - everything seems to be working fine for me, which theme are you trying to use?

**Comment by jgallen23** [comment]
any base16 one, I'm now using base16-solarized-light and same issue.

**Comment by jgallen23** [comment]
setting base16colorspace=256 fixed it
